### ISSUE TITLE
Getting this when installing

### ISSUE THREAD

**Issue by CrouchingWorm** [arallsopp/hass-hue-icons#47]
Hey there,
I've installed your repo today - through HACS.
When i click install the install box doesn't progress past this point:
![image](https://user-images.githubusercontent.com/35030235/131783826-baa40eac-de17-4231-a1cc-d741806e0760.png)

BUT, when i check the /community/hass-hue-icons it is populated.
I am able to use the icons once I clear the cache in my edge browser.

When I get back into HACS interface I see this error:
![image](https://user-images.githubusercontent.com/35030235/131783973-c9c6628a-bf45-4dc3-88d8-f6c8824838b1.png)
When I click this notification it shows this:
![image](https://user-images.githubusercontent.com/35030235/131784020-6c989bc6-a536-4f6f-9880-5b33883d6c94.png)
When I check my logs I see:
![image](https://user-images.githubusercontent.com/35030235/131784099-c304b487-1951-4049-b2ff-5fe239ccd4fb.png)

I'm running:
Supervised HA core-2021.8.8, 
HACS Frontend Version:
20210822172723 (integration: 1.15.1)

Weird..

**Comment by CrouchingWorm** [comment]
I've since manually added the entry into my resources.yaml.
The error has disappeared now.
So if you'd like to close this you can..
PS. Excellent work, thank you so much!

**Comment by arallsopp** [comment]
Looks like this was a one off. I've pushed an updated version with some new icons. Does HACS tell you there's an update? If not, might be worth installing from HACS, just so that you keep up with future versions :)

Assuming all good, I'll close this shortly.

**Comment by CrouchingWorm** [comment]
Unfortunately still happening.
I tried updating from my mobile.
Didn’t get past this point.
I’ve shut the window to navigate elsewhere.
Looks like it’s my environment?
When I’m on a pc next I’ll check the time stamp of the files in the folder
to see if they’re the new ones.

Thank you for the prompt response. :)

**Comment by CrouchingWorm** [comment]
Okay, I've checked the timestamps and it seems the files have indeed
updated.
I think close this as it might just be me, I can update through HACS, but
have to manually bomb out of it.
Weird, but that's how I roll it seems.

**Comment by arallsopp** [comment]
Thanks for the update. I'll close this now, but perhaps you might raise a ticket with the HACS folks. The community is pretty good and I'm hopeful you'd get help. 

Glad you found a way forwards for now. The version you have installed is visible in the developer console (assuming you're on a desktop browser) btw. :)

**Comment by jchhenderson** [comment]
I have the exact same problem.

I installed it (OK) yesterday and today it no longer loads.
I have manually added the `extra_module_url` but still no joy.

I uninstalled/reinstalled and, whilst the I can see the files have been installed, it is stuck ion the same screen as the OP and shows as "not loaded".

**Comment by arallsopp** [comment]
Interesting... looking in. Does your JavaScript console show any output related to hass-hue-icons? A version number, for example? Do you have any other plugins from HACS installed?

**Comment by jchhenderson** [comment]
Hi @arallsopp thanks for such a speedy response!

Actually I got it working but, in addition to:
```
frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
```

 I also had to add:
```
  resources:
    - url: /hacsfiles/hass-hue-icons/hass-hue-icons.js
      type: js
```
I can't see this documented anywhere (purely a guess based off other custom:cards).

**Comment by arallsopp** [comment]
HACS should have done that for you, I believe. 

I'll leave this here as it might help others. 

Well done for resolving.

**Comment by jchhenderson** [comment]
I had to manually add `resources:` for all my HACS this morning so something clearly changed for me.

thanks!

**Comment by arallsopp** [comment]
Good to know. Wonder if that's to do with storage mode, as that seems to have been a similar problem before. 

https://github.com/hacs/integration/issues/1234#issuecomment-633042663

**Comment by jchhenderson** [comment]
Oh, well done!  That was probably it.  I changed to yaml mode yesterday so I could be in control of the top dash (is it possible to to control the top dash and still be in storage?

**Comment by arallsopp** [comment]
My guess is that HACS makes changes based upon the first dash it encounters, and that changing mode after the event doesn't trigger any kind of migration so the config that was originally applied no longer gets read. It's guesswork, of course. I'm but a lowly plug-in developer who likes making pretty shapes and colouring things in. The intricacies of HACS and HA's inner workings are beyond me :)

**Comment by jchhenderson** [comment]
> I'm but a lowly plug-in developer who likes making pretty shapes and colouring things in.

definitely not lowly and please don't stop!! 👍
